-- AI-Powered College & Hostel Complaint Management and Grievance Redressal System
-- MySQL Schema (also auto-generated by Sequelize sync; provided here for manual setup)

CREATE DATABASE IF NOT EXISTS grievance_system;
USE grievance_system;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('student','admin','warden') NOT NULL DEFAULT 'student',
  hostel VARCHAR(100),
  department VARCHAR(100),
  roomNumber VARCHAR(20),
  phone VARCHAR(20),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS complaints (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  student_name VARCHAR(120) NOT NULL,
  category ENUM(
    'Hostel Maintenance','Electricity','Water Problem','Food Quality',
    'Cleanliness','Internet Issue','Ragging','Security','Academic Issue','Other'
  ) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(150),
  hostel_or_dept VARCHAR(120),
  priority ENUM('Low','Medium','High','Critical') NOT NULL DEFAULT 'Medium',
  status ENUM('Submitted','Under Review','Assigned','In Progress','Resolved','Rejected','Escalated') NOT NULL DEFAULT 'Submitted',
  assigned_to VARCHAR(120),
  resolution_notes TEXT,
  resolved_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_suggestions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  complaint_id INT NOT NULL,
  suggestion TEXT NOT NULL,
  category VARCHAR(80),
  solution TEXT,
  estimated_resolution_time VARCHAR(50),
  confidence FLOAT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS escalations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  complaint_id INT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  status ENUM('Open','Reviewed','Closed') NOT NULL DEFAULT 'Open',
  FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  complaint_id INT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE
);

-- Helpful indexes
CREATE INDEX idx_complaints_status ON complaints(status);
CREATE INDEX idx_complaints_category ON complaints(category);
CREATE INDEX idx_complaints_user ON complaints(user_id);
